apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
    app: milvus
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
      app: milvus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/milvus: "true"
        io.kompose.service: minio
        app: milvus
    spec:
      containers:
        - args:
            - minio
            - server
            - /minio_data
            - --console-address
            - :9001
          env:
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_SECRET_KEY
              value: minioadmin
          image: minio/minio:RELEASE.2023-03-20T20-16-18Z
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9000/minio/health/live
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 20
          name: milvus-minio
          ports:
            - containerPort: 9001
              #hostPort: 9001
              protocol: TCP
            - containerPort: 9000
              #hostPort: 9000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /minio_data
              name: minio-claim0
      restartPolicy: Always
      volumes:
        - name: minio-claim0
          persistentVolumeClaim:
            claimName: minio-claim0
status: {}
