apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: haproxy
    app: milvus
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: haproxy
      app: milvus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/milvus: "true"
        io.kompose.service: haproxy
        app: milvus
    spec:
      containers:
        - args:
          image: haproxy:latest
          name: haproxy
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/milvus
              name: haproxy-claim0
      restartPolicy: Always
      volumes:
        - name: haproxy-claim0
          persistentVolumeClaim:
            claimName: haproxy-claim0
status: {}
